replicaCount: 1

# Image configuration for the blog-web application
image:
  repository: anuragox/blog_web
  pullPolicy: IfNotPresent
  tag: "3e6a2709c1d8a72cb6e256155c64be26ef016de9"

# MongoDB configuration
mongo:
  image:
    repository: mongo
    tag: "3e6a2709c1d8a72cb6e256155c64be26ef016de9"
  service:
    port: 27017
  
# BLog web application configuration
blogWeb:
  replicas: 1
  service:
    port: 5000