replicaCount: 1

# Image configuration for the blog-web application
image:
  repository: anuragox/blog_web
  pullPolicy: IfNotPresent
  tag: "a946894d22cd44f7802d208b8649a3342d83b9dc"

# MongoDB configuration
mongo:
  image:
    repository: mongo
    tag: "a946894d22cd44f7802d208b8649a3342d83b9dc"
  service:
    port: 27017

# BLog web application configuration
blogWeb:
  replicas: 1
  service:
    port: 5000

