replicaCount: 1

# Image configuration for the blog-web application
image:
  repository: anuragox/blog_web
  pullPolicy: IfNotPresent
  tag: "a965dda577ac7c93531bb76dfd9cfe9eecd9491c"

# MongoDB configuration
mongo:
  image:
    repository: mongo
    tag: "a965dda577ac7c93531bb76dfd9cfe9eecd9491c"
  service:
    port: 27017
  
# BLog web application configuration
blogWeb:
  replicas: 1
  service:
    port: 5000