replicaCount: 1

# Image configuration for the blog-web application
image:
  repository: anuragox/blog_web
  pullPolicy: IfNotPresent
  tag: "f1b910838c251fc63e9d1842987a64689d6b6beb"

# MongoDB configuration
mongo:
  image:
    repository: mongo
    tag: "f1b910838c251fc63e9d1842987a64689d6b6beb"
  service:
    port: 27017
  
# BLog web application configuration
blogWeb:
  replicas: 1
  service:
    port: 5000