replicaCount: 1

# Image configuration for the blog-web application
image:
  repository: anuragox/blog_web
  pullPolicy: IfNotPresent
  tag: "bd998049b84d4414b9835c554023a222edfeadc3"

# MongoDB configuration
mongo:
  image:
    repository: mongo
    tag: "bd998049b84d4414b9835c554023a222edfeadc3"
  service:
    port: 27017

# BLog web application configuration
blogWeb:
  replicas: 1
  service:
    port: 5000

