replicaCount: 1

# Image configuration for the blog-web application
image:
  repository: anuragox/blog_web
  pullPolicy: IfNotPresent
  tag: "eb998b72f156ce9a9cc44c5958bc526bf98b1df9"

# MongoDB configuration
mongo:
  image:
    repository: mongo
    tag: "eb998b72f156ce9a9cc44c5958bc526bf98b1df9"
  service:
    port: 27017

# BLog web application configuration
blogWeb:
  replicas: 1
  service:
    port: 5000

