replicaCount: 1

# Image configuration for the blog-web application
image:
  repository: anuragox/blog_web
  pullPolicy: IfNotPresent
  tag: "17f9115733fbd6e633779a019bceb2613819f5e0"

# MongoDB configuration
mongo:
  image:
    repository: mongo
    tag: "17f9115733fbd6e633779a019bceb2613819f5e0"
  service:
    port: 27017

# BLog web application configuration
blogWeb:
  replicas: 1
  service:
    port: 5000

