apiVersion: v1
kind: Secret
metadata:
  name: blog-web-secrets
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYjovL2xvY2FsaG9zdDoyNzAxNy9ibG9nREI=
  SECRET: S2V5Ym9hcmQgY2F0
  JWT_SECRET: TXlTZWNyZXRCbG9n
  EMAIL_USER: YW51cmFncmtvNDIwMDRAZ21haWwuY29t
  EMAIL_PASS: cGRtby1mdnNuLWd2ZXcta255eA==
  REDIS_URL: cmVkaXM6Ly9sb2NhbGhvc3Q6NjM3OQ==
