name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    # - name: Run tests
    #   run: npm test

    # - name: Static code analysis
    #   run: npx eslint .
    #   env:
    #     CI: true

  docker:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t anuragox/blog_web:${{ github.sha }} .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker push anuragox/blog_web:${{ github.sha }}

  update-helm-chart:
    runs-on: ubuntu-latest

    needs: docker

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN_GIT }}

    - name: Update Helm chart with new image tag
      run: |
        sed -i 's/tag: .*/tag: "${{github.sha}}"/' helm/blog-web-chart/values.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "amnrag889@gmail.com"
        git config --global user.name "anurag-xo"
        git add ./helm/blog-web-chart/values.yaml
        git commit -m "Update tag in Helm chart"
        git push
      env:
        TOKEN_GIT: ${{ secrets.TOKEN_GIT }} # Use the GitHub token for authentication

    - name: Deploy Helm chart
      run: |
        helm upgrade --install blog-web ./helm/blog-web-chart/values.yaml --set image.tag=${{ github.sha }}
