name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_IMAGE: anuragox/blog_web
  DOCKER_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

      - name: Set up Minikube
        uses: medyagh/setup-minikube@master

      - name: Configure Minikube and wait for Ingress
        run: |
          minikube addons enable ingress
          minikube status
          
          # Wait for the ingress controller pods to be ready
          echo "Waiting for ingress-nginx pods to be ready..."
          kubectl wait --namespace ingress-nginx \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/component=controller \
            --timeout=300s

      - name: Deploy to Minikube
        run: |
          # Update the image in deployment yaml
          sed -i "s|anuragox/blog_web|${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}|g" k8s/manifests/deployment.yaml
          
          # Apply MongoDB resources first
          kubectl apply -f k8s/manifests/mong-deployment.yaml
          kubectl apply -f k8s/manifests/mongo-service.yaml
          
          # Wait for MongoDB to be ready
          kubectl wait --for=condition=available deployment/mongo --timeout=300s
          
          # Apply application resources
          kubectl apply -f k8s/manifests/deployment.yaml
          kubectl apply -f k8s/manifests/service.yaml
          
          # Wait for blog-web deployment to be ready
          kubectl wait --for=condition=available deployment/blog-web --timeout=300s
          
          # Wait a bit more for the ingress controller to be fully ready
          sleep 30
          
          # Apply ingress last
          kubectl apply -f k8s/manifests/ingress.yaml

      - name: Test deployment
        run: |
          kubectl get all
          kubectl get ingress
          echo "$(minikube ip) blog-web.local" | sudo tee -a /etc/hosts
          sleep 30
          curl -H "Host: blog-web.local" http://$(minikube ip)/