name: CI Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'helm/**'
jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Install kubeval
      run: |
        wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
        tar xf kubeval-linux-amd64.tar.gz
        sudo mv kubeval /usr/local/bin

    - name: Validate Kubernetes manifests
      run: |
        kubeval --strict k8s/*.yaml

    - name: Lint Kubernetes manifests
      uses: azure/k8s-lint@v1
      with:
        manifests: |
          k8s/manifests/deployment.yaml
          k8s/manifests/ingress.yaml
          k8s/manifests/mongo-deployment.yaml
          k8s/manifests/mongo-service.yaml
          k8s/manifests/service.yaml

  # Optional: Add security scanning
  security-scan:
    runs-on: ubuntu-latest
    needs: validate
    
    steps:
    - uses: actions/checkout@v4

    - name: Run Kubesec scan
      uses: controlplaneio/kubesec-action@master
      with:
        input: k8s/*.yaml
        format: human
        exit-code: "0"

  # Optional: Add test deployment to a test cluster
  # test-deploy:
  #   runs-on: ubuntu-latest
  #   needs: [validate, security-scan]
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  # 
  #   steps:
  #   - uses: actions/checkout@v4
  # 
  #   - name: Set up kubeconfig
  #     uses: azure/k8s-set-context@v3
  #     with:
  #       method: kubeconfig
  #       kubeconfig: ${{ secrets.KUBE_CONFIG }}
  # 
  #   - name: Deploy to test cluster
  #     run: |
  #       kubectl apply -f k8s/ 