name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - "helm/**"
      - "k8s/**"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Updated to Node.js 18

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: |
          docker build -t anuragox/blog_web:${{ github.sha }} .
          docker tag anuragox/blog_web:${{ github.sha }} anuragox/blog_web:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push anuragox/blog_web:${{ github.sha }}
          docker push anuragox/blog_web:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Docker image to ECR
        run: |
          docker tag anuragox/blog_web:${{ github.sha }} ${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}
          docker tag anuragox/blog_web:latest ${{ secrets.ECR_REPOSITORY }}:latest
          docker push ${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}
          docker push ${{ secrets.ECR_REPOSITORY }}:latest

  update-helm-chart:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN_GIT }}

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Lint Helm chart
        run: helm lint ./helm/blog-web-chart

      - name: Update Helm chart with new image tag
        run: |
          sed -i 's/tag: .*/tag: "${{github.sha}}"/' helm/blog-web-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "amnrag889@gmail.com"
          git config --global user.name "anurag-xo"
          git add ./helm/blog-web-chart/values.yaml
          git commit -m "Update tag in Helm chart"
          git push
        env:
          TOKEN_GIT: ${{ secrets.TOKEN_GIT }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} "
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}
            docker pull ${{ secrets.ECR_REPOSITORY }}:latest
            cd /home/ec2-user/Blog-web  # Navigate to the correct directory
            docker-compose down
            docker-compose up -d
          "
