name: CI Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'helm/**'

jobs:
  build:
    # ... (previous build job remains the same)

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          
          # Add this to make minikube IP accessible (if using minikube)
          echo "${{ secrets.MINIKUBE_IP }} $(kubectl config view -o jsonpath='{.clusters[0].cluster.server}' | sed 's#https://##' | sed 's/:8443//')" | sudo tee -a /etc/hosts

      - name: Create namespace if not exists
        run: |
          kubectl create namespace production --dry-run=client -o yaml | kubectl apply -f -

      - name: Package Helm chart
        run: |
          helm package ./helm/blog-web-chart

      - name: Deploy to Kubernetes using Helm
        run: |
          helm upgrade --install blog-web ./blog-web-chart-*.tgz \
            --namespace production \
            --values ./helm/blog-web-chart/values.yaml \
            --debug